# Generated by Django 5.1.1 on 2024-09-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoDeEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=100)),
                ('comodo', models.CharField(max_length=100)),
                ('gasto', models.CharField(max_length=100)),
            ],
        ),
    ]
