# Generated by Django 5.1.1 on 2024-09-29 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.locacao')),
            ],
        ),
    ]
