# Generated by Django 5.1.1 on 2024-09-29 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pontodeenergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('nome', models.CharField(max_length=100)),
                ('comodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comodo')),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.locacao')),
            ],
        ),
    ]
