# Generated by Django 5.1.1 on 2024-09-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pontodeenergia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontodeenergia',
            name='gasto',
        ),
        migrations.AddField(
            model_name='pontodeenergia',
            name='gastos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
