# Generated by Django 5.1.1 on 2024-09-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pontodeenergia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontodeenergia',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
