# Generated by Django 5.1 on 2024-11-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pontodeenergia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontodeenergia',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pontodeenergia',
            name='gastos',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
