# Generated by Django 5.1 on 2024-11-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pontodeenergia_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontodeenergia',
            name='gastos',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
