# Generated by Django 5.1 on 2024-11-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_pontodeenergia_gastos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontodeenergia',
            name='gastos',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
